# Generated by Django 3.1.5 on 2021-01-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('ig_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('profile_picture_url', models.CharField(blank=True, max_length=2000)),
                ('follows_count', models.IntegerField(blank=True)),
                ('followers_count', models.IntegerField(blank=True)),
                ('media_count', models.IntegerField(blank=True)),
                ('id', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
